# Generated by Django 5.0 on 2024-01-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=0, verbose_name='идентификатор'),
            preserve_default=False,
        ),
    ]
